//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEJA_KHC_WEB_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Geja_KHC_Entities : DbContext
    {
        public Geja_KHC_Entities()
            : base("name=Geja_KHC_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddressInfo> AddressInfo { get; set; }
        public virtual DbSet<EducationAndJobInfo> EducationAndJobInfo { get; set; }
        public virtual DbSet<EducationLevel> EducationLevel { get; set; }
        public virtual DbSet<FamilyInfo> FamilyInfo { get; set; }
        public virtual DbSet<FieldOfStudy> FieldOfStudy { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<HouseOwnershipType> HouseOwnershipType { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<JobType> JobType { get; set; }
        public virtual DbSet<MaritalStatus> MaritalStatus { get; set; }
        public virtual DbSet<MemberService> MemberService { get; set; }
        public virtual DbSet<MembershipMeans> MembershipMeans { get; set; }
        public virtual DbSet<Month> Month { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceType> ServiceType { get; set; }
        public virtual DbSet<Subcity> Subcity { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<EducationLevelByGroup> EducationLevelByGroup { get; set; }
        public virtual DbSet<GenderByGroup> GenderByGroup { get; set; }
        public virtual DbSet<MaritalStatusByGroup> MaritalStatusByGroup { get; set; }
        public virtual DbSet<MembershipMeansByGroup> MembershipMeansByGroup { get; set; }
        public virtual DbSet<SubcityByGroup> SubcityByGroup { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<MemberPhoto> MemberPhoto { get; set; }
    }
}
