//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEJA_KHC_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.MemberService = new HashSet<MemberService>();
        }
    
        public string MemberId { get; set; }
        public string FullName { get; set; }
        public string MotherName { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> BirthDate { get; set; }
        public Nullable<int> BirthMonthId { get; set; }
        public Nullable<int> BirthYear { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> MembershipDate { get; set; }
        public Nullable<int> MembershipMonthId { get; set; }
        public Nullable<int> MembershipYear { get; set; }
        public Nullable<int> MembershipMeansId { get; set; }
        public string NoServiceReason { get; set; }
        public string NoServiceReason2 { get; set; }
        public string Remark { get; set; }
    
        public virtual AddressInfo AddressInfo { get; set; }
        public virtual EducationAndJobInfo EducationAndJobInfo { get; set; }
        public virtual FamilyInfo FamilyInfo { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Group Group { get; set; }
        public virtual Month Month { get; set; }
        public virtual Month Month1 { get; set; }
        public virtual MembershipMeans MembershipMeans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberService> MemberService { get; set; }
        public virtual MemberPhoto MemberPhoto { get; set; }
    }
}
