//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEJA_KHC_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationAndJobInfo
    {
        public string MemberId { get; set; }
        public Nullable<int> EducationLevelId { get; set; }
        public Nullable<int> FieldOfStudyId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> JobTypeId { get; set; }
    
        public virtual EducationLevel EducationLevel { get; set; }
        public virtual FieldOfStudy FieldOfStudy { get; set; }
        public virtual Job Job { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual Member Member { get; set; }
    }
}
