//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEJA_KHC_MAUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubcityByGroup
    {
        public Nullable<long> RowId { get; set; }
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Unknown { get; set; }
        public Nullable<int> Lideta { get; set; }
        public Nullable<int> AddisKetema { get; set; }
        public Nullable<int> KolfeKeraniyo { get; set; }
        public Nullable<int> Arada { get; set; }
        public Nullable<int> Gulele { get; set; }
        public Nullable<int> Kirkos { get; set; }
        public Nullable<int> Yeka { get; set; }
        public Nullable<int> Bole { get; set; }
        public Nullable<int> NifasSilkLafto { get; set; }
        public Nullable<int> AkakiKality { get; set; }
        public Nullable<int> LemiKura { get; set; }
    }
}
